name: Build and test MacOS

on:
  push:
    branches: [ "ci" ]
    paths:
      - 'src/**'
      - '!src/Common/Language.xml'
      - '.github/workflows/build-macos.yml'
  pull_request:
    branches: [ "ci" ]
    paths:
      - 'src/**'
      - '!src/Common/Language.xml'
      - '.github/workflows/build-macos.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  WXWIDGETS_VERSION: 3.2.5
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  macos-12-macfuse:

    runs-on: macos-12
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v4
    - name: Cache wxwidgets build
      id: cache-wxwidgets
      uses: actions/cache@v3

      with:
        path: ${{ github.workspace }}/src/wxrelease
        key: ${{ runner.os }}-${{ env.WXWIDGETS_VERSION }}-${{ hashFiles('src/Makefile') }}
        restore-keys: ${{ runner.os }}-${{ env.WXWIDGETS_VERSION }}-${{ hashFiles('src/Makefile') }}
  
    - if: ${{ steps.cache-wxwidgets.outputs.cache-hit != 'true' }}
      name: Download and extract wxWidgets
      run: |
        gh release download --repo wxWidgets/wxWidgets v$WXWIDGETS_VERSION -p "wxWidgets-$WXWIDGETS_VERSION.tar.bz2" && \
        mkdir "wxWidgets-$WXWIDGETS_VERSION" && \
        tar -xf "wxWidgets-$WXWIDGETS_VERSION.tar.bz2" -C "wxWidgets-$WXWIDGETS_VERSION" --strip-components 1
        make WXSTATIC=FULL WITHGTK3=1 WX_ROOT=${{ github.workspace }}/wxWidgets-$WXWIDGETS_VERSION -C src wxbuild

    - name: Install pcsc-lite
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install pcsc-lite
    - name: Install yasm
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install yasm
    - name: Install macfuse
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask macfuse
    - name: Build VeraCrypt
      run: make WXSTATIC=FULL WITHGTK3=1 WX_ROOT=${{ github.workspace }}/wxWidgets-$WXWIDGETS_VERSION -C src
    - name: Test binary
      run: |
        ./src/Main/veracrypt --text --test && ./src/Main/veracrypt --text --version
    #- name: Test volumes
    #  run: |
    #    sudo ./src/Main/veracrypt --text --non-interactive Tests/test.sha256.hc --hash sha256 --slot 1 --password test --mount-options=ro && \
    #    sudo ./src/Main/veracrypt --text --non-interactive Tests/test.sha512.hc --hash sha512 --slot 2 --password test --mount-options=ro && \
    #    sudo ./src/Main/veracrypt --text --non-interactive Tests/test.streebog.hc --hash streebog --slot 3 --password test --mount-options=ro && \
    #    sudo ./src/Main/veracrypt --text --non-interactive Tests/test.whirlpool.hc --hash whirlpool --slot 4 --password test --mount-options=ro && \
    #    sudo ./src/Main/veracrypt --text --list && \
    #    sudo ./src/Main/veracrypt -d
