name: C/C++ CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

env:
  WXWIDGETS_VERSION: 3.2.5

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download and extract wxWidgets 3.2.5
      run: gh release download --repo wxWidgets/wxWidgets v3.2.5 -p 'wxWidgets-3.2.5.tar.bz2' && mkdir '../wxWidgets-3.2.5' && tar -xf 'wxWidgets-3.2.5.tar.bz2' -C '../wxWidgets-3.2.5' --strip-components 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install libpcsclite-dev
      run: sudo apt-get install -y libpcsclite-dev
    - name: Install libfuse-dev
      run: sudo apt-get install -y libfuse-dev
    - name: Install yasm
      run: sudo apt-get install -y yasm
    - name: Install libgtk-3-dev
      run: sudo apt-get install -y libgtk-3-dev
    - name: Build wxWidgets
      run: make WXSTATIC=1 WITHGTK3=1 WX_ROOT=${{ github.workspace }}/../wxWidgets-3.2.5 -C src wxbuild
    #- name: Build VeraCrypt
    #  run: make WXSTATIC=1 WITHGTK3=1 WX_ROOT=${{ github.workspace }}/../wxWidgets-3.2.5 -C src
    - name: Build VeraCrypt
      run: src/Build/build_cmake_deb.sh "GUI" "WXSTATIC" ""
    - name: ls
      run: ls -la VeraCrypt_Packaging
    - name: Test binary
      run: |
        sudo ./src/Main/veracrypt --text --non-interactive Tests/test.sha256.hc --hash sha256 --slot 1 --password test --mount-options=ro && \
        sudo ./src/Main/veracrypt --text --non-interactive Tests/test.sha512.hc --hash sha512 --slot 2 --password test --mount-options=ro && \
        sudo ./src/Main/veracrypt --text --non-interactive Tests/test.streebog.hc --hash streebog --slot 3 --password test --mount-options=ro && \
        sudo ./src/Main/veracrypt --text --non-interactive Tests/test.whirlpool.hc --hash whirlpool --slot 4 --password test --mount-options=ro && \
        sudo ./src/Main/veracrypt --text --list && \
        sudo ./src/Main/veracrypt -d
