name: C/C++ CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libpcsclite
      run: sudo apt-get install -y libpcsclite
    - name: make
      run: make -C src
    - name: test
      run: echo "Testing"
      
